### PR TITLE
Improve exercises

### PR DESCRIPTION
**Pull request by sofusalbertsen**

### CODE REVIEW

**Comment by sofusalbertsen** [comment]
As long as one of you thinks it's good enough, just merge or comment :)

**Comment by zanderhavgaard** [comment]
Resolve the conflicts, otherwise I think it looks good :+1:

**Review by zanderhavgaard — APPROVED** [review]

**Comment by sofusalbertsen** [comment]
Will do, thanks!

**Comment by sofusalbertsen** [comment]
@zanderhavgaard or @dwawrzkiewicz-eficode can I get one of you to look through this once more?

**Pull request merged**
